//
//  ExchangeRate.swift
//  ExchangeRateCalculation
//
//  Created by 이수현 on 4/15/25.
//

import Foundation

enum Fluctuation: String, CaseIterable {
    case increase
    case decrease
    case same

    init(fluctuation: String) {
        switch fluctuation {
        case "increase": self = .increase
        case "decrease": self = .decrease
        default: self = .same
        }
    }

    init(prevRate: Double, rate: Double) {
        if abs(rate - prevRate) <= 0.01 {
            self = .same
        } else if rate - prevRate > 0 {
            self = .increase
        } else {
            self = .decrease
        }
    }
}

struct ExchangeRate {
    let country: String
    let currency: String
    let rate: Double
    private(set) var fluctuation: Fluctuation
    private(set) var isFavorite: Bool

    mutating func setIsFavorite(isFavorite: Bool) {
        self.isFavorite = isFavorite
    }

    init(currency: String, rate: Double, fluctuation: Fluctuation, isFavorite: Bool = false) {
        self.country = ExchangeRate.currencyToCountryMap[currency] ?? ""
        self.currency = currency
        self.rate = rate
        self.fluctuation = fluctuation
        self.isFavorite = isFavorite
    }
}

typealias ExchangeRates = [ExchangeRate]


extension ExchangeRate {
    static let currencyToCountryMap = [
        "USD": "미국",
        "AED": "아랍에미리트",
        "AFN": "아프가니스탄",
        "ALL": "알바니아",
        "AMD": "아르메니아",
        "ANG": "네덜란드령 안틸레스",
        "AOA": "앙골라",
        "ARS": "아르헨티나",
        "AUD": "오스트레일리아",
        "AWG": "아루바",
        "AZN": "아제르바이잔",
        "BAM": "보스니아 헤르체고비나",
        "BBD": "바베이도스",
        "BDT": "방글라데시",
        "BGN": "불가리아",
        "BHD": "바레인",
        "BIF": "부룬디",
        "BMD": "버뮤다",
        "BND": "브루나이",
        "BOB": "볼리비아",
        "BRL": "브라질",
        "BSD": "바하마",
        "BTN": "부탄",
        "BWP": "보츠와나",
        "BYN": "벨라루스",
        "BZD": "벨리즈",
        "CAD": "캐나다",
        "CDF": "콩고민주공화국",
        "CHF": "스위스",
        "CLP": "칠레",
        "CNY": "중국",
        "COP": "콜롬비아",
        "CRC": "코스타리카",
        "CUP": "쿠바",
        "CVE": "카보베르데",
        "CZK": "체코",
        "DJF": "지부티",
        "DKK": "덴마크",
        "DOP": "도미니카공화국",
        "DZD": "알제리",
        "EGP": "이집트",
        "ERN": "에리트레아",
        "ETB": "에티오피아",
        "EUR": "유럽연합",
        "FJD": "피지",
        "FKP": "포클랜드제도",
        "FOK": "페로제도",
        "GBP": "영국",
        "GEL": "조지아",
        "GGP": "건지",
        "GHS": "가나",
        "GIP": "지브롤터",
        "GMD": "감비아",
        "GNF": "기니",
        "GTQ": "과테말라",
        "GYD": "가이아나",
        "HKD": "홍콩",
        "HNL": "온두라스",
        "HRK": "크로아티아",
        "HTG": "아이티",
        "HUF": "헝가리",
        "IDR": "인도네시아",
        "ILS": "이스라엘",
        "IMP": "맨섬",
        "INR": "인도",
        "IQD": "이라크",
        "IRR": "이란",
        "ISK": "아이슬란드",
        "JEP": "저지섬",
        "JMD": "자메이카",
        "JOD": "요르단",
        "JPY": "일본",
        "KES": "케냐",
        "KGS": "키르기스스탄",
        "KHR": "캄보디아",
        "KID": "키리바시",
        "KMF": "코모로",
        "KRW": "대한민국",
        "KWD": "쿠웨이트",
        "KYD": "케이맨 제도",
        "KZT": "카자흐스탄",
        "LAK": "라오스",
        "LBP": "레바논",
        "LKR": "스리랑카",
        "LRD": "라이베리아",
        "LSL": "레소토",
        "LYD": "리비아",
        "MAD": "모로코",
        "MDL": "몰도바",
        "MGA": "마다가스카르",
        "MKD": "북마케도니아",
        "MMK": "미얀마",
        "MNT": "몽골",
        "MOP": "마카오",
        "MRU": "모리타니",
        "MUR": "모리셔스",
        "MVR": "몰디브",
        "MWK": "말라위",
        "MXN": "멕시코",
        "MYR": "말레이시아",
        "MZN": "모잠비크",
        "NAD": "나미비아",
        "NGN": "나이지리아",
        "NIO": "니카라과",
        "NOK": "노르웨이",
        "NPR": "네팔",
        "NZD": "뉴질랜드",
        "OMR": "오만",
        "PAB": "파나마",
        "PEN": "페루",
        "PGK": "파푸아뉴기니",
        "PHP": "필리핀",
        "PKR": "파키스탄",
        "PLN": "폴란드",
        "PYG": "파라과이",
        "QAR": "카타르",
        "RON": "루마니아",
        "RSD": "세르비아",
        "RUB": "러시아",
        "RWF": "르완다",
        "SAR": "사우디아라비아",
        "SBD": "솔로몬 제도",
        "SCR": "세이셸",
        "SDG": "수단",
        "SEK": "스웨덴",
        "SGD": "싱가포르",
        "SHP": "세인트헬레나",
        "SLE": "시에라리온",
        "SLL": "시에라리온",
        "SOS": "소말리아",
        "SRD": "수리남",
        "SSP": "남수단",
        "STN": "상투메 프린시페",
        "SYP": "시리아",
        "SZL": "에스와티니",
        "THB": "태국",
        "TJS": "타지키스탄",
        "TMT": "투르크메니스탄",
        "TND": "튀니지",
        "TOP": "통가",
        "TRY": "튀르키예",
        "TTD": "트리니다드 토바고",
        "TVD": "투발루",
        "TWD": "대만",
        "TZS": "탄자니아",
        "UAH": "우크라이나",
        "UGX": "우간다",
        "UYU": "우루과이",
        "UZS": "우즈베키스탄",
        "VES": "베네수엘라",
        "VND": "베트남",
        "VUV": "바누아투",
        "WST": "사모아",
        "XAF": "중앙아프리카 CFA 프랑",
        "XCD": "동카리브 제도",
        "XCG": "가상통화 (Crypto Generic)",
        "XDR": "IMF 특별인출권",
        "XOF": "서아프리카 CFA 프랑",
        "XPF": "프랑스령 폴리네시아",
        "YER": "예멘",
        "ZAR": "남아프리카 공화국",
        "ZMW": "잠비아",
        "ZWL": "짐바브웨"
    ]

    static let mockExchangeRates: [ExchangeRate] = [
        ExchangeRate(currency: "USD", rate: 1.0, fluctuation: .increase),
        ExchangeRate(currency: "AED", rate: 3.6725, fluctuation: .same),
        ExchangeRate(currency: "AFN", rate: 72.0735, fluctuation: .increase),
        ExchangeRate(currency: "ALL", rate: 86.8215, fluctuation: .decrease),
        ExchangeRate(currency: "AMD", rate: 390.9911, fluctuation: .decrease),
        ExchangeRate(currency: "ANG", rate: 1.7822, fluctuation: .decrease),
        ExchangeRate(currency: "AOA", rate: 918.3832, fluctuation: .decrease),
        ExchangeRate(currency: "ARS", rate: 1172.7765, fluctuation: .decrease),
        ExchangeRate(currency: "AUD", rate: 1.6245, fluctuation: .increase),
        ExchangeRate(currency: "AWG", rate: 1.8521, fluctuation: .increase),
        ExchangeRate(currency: "AZN", rate: 1.7089, fluctuation: .increase),
        ExchangeRate(currency: "BAM", rate: 1.7562, fluctuation: .increase),
        ExchangeRate(currency: "BBD", rate: 2.0913, fluctuation: .increase),
        ExchangeRate(currency: "BDT", rate: 121.5483, fluctuation: .same),
        ExchangeRate(currency: "BGN", rate: 1.7569, fluctuation: .increase),
        ExchangeRate(currency: "BHD", rate: 0.3817, fluctuation: .increase),
        ExchangeRate(currency: "BIF", rate: 2970.5862, fluctuation: .decrease),
        ExchangeRate(currency: "BMD", rate: 1.0872, fluctuation: .increase),
        ExchangeRate(currency: "BND", rate: 1.3147, fluctuation: .increase),
        ExchangeRate(currency: "BOB", rate: 6.9221, fluctuation: .decrease),
        ExchangeRate(currency: "BRL", rate: 5.8937, fluctuation: .increase),
        ExchangeRate(currency: "BSD", rate: 0.9921, fluctuation: .decrease),
        ExchangeRate(currency: "BTN", rate: 85.4723, fluctuation: .decrease),
        ExchangeRate(currency: "BWP", rate: 13.7994, fluctuation: .increase),
        ExchangeRate(currency: "BYN", rate: 3.0908, fluctuation: .decrease),
        ExchangeRate(currency: "BZD", rate: 2.0783, fluctuation: .increase),
        ExchangeRate(currency: "CAD", rate: 1.4589, fluctuation: .increase),
        ExchangeRate(currency: "CDF", rate: 2916.9372, fluctuation: .increase),
        ExchangeRate(currency: "CHF", rate: 0.8213, fluctuation: .increase),
        ExchangeRate(currency: "CLP", rate: 967.3012, fluctuation: .decrease),
        ExchangeRate(currency: "CNY", rate: 7.3627, fluctuation: .increase),
        ExchangeRate(currency: "COP", rate: 4316.0582, fluctuation: .decrease),
        ExchangeRate(currency: "CRC", rate: 502.1237, fluctuation: .decrease),
        ExchangeRate(currency: "CUP", rate: 24.0572, fluctuation: .increase),
        ExchangeRate(currency: "CVE", rate: 96.4872, fluctuation: .decrease),
        ExchangeRate(currency: "CZK", rate: 22.0124, fluctuation: .increase),
        ExchangeRate(currency: "DJF", rate: 177.6812, fluctuation: .decrease),
        ExchangeRate(currency: "DKK", rate: 6.6085, fluctuation: .increase),
        ExchangeRate(currency: "DOP", rate: 60.1249, fluctuation: .increase),
        ExchangeRate(currency: "DZD", rate: 132.3812, fluctuation: .decrease),
        ExchangeRate(currency: "EGP", rate: 51.0723, fluctuation: .decrease),
        ExchangeRate(currency: "ERN", rate: 15.0823, fluctuation: .increase),
        ExchangeRate(currency: "ETB", rate: 133.3896, fluctuation: .increase),
        ExchangeRate(currency: "EUR", rate: 0.8843, fluctuation: .increase),
        ExchangeRate(currency: "FJD", rate: 2.2947, fluctuation: .increase),
        ExchangeRate(currency: "FKP", rate: 0.7568, fluctuation: .increase),
        ExchangeRate(currency: "FOK", rate: 6.5371, fluctuation: .decrease),
        ExchangeRate(currency: "GBP", rate: 0.7521, fluctuation: .decrease),
        ExchangeRate(currency: "GEL", rate: 2.7564, fluctuation: .increase),
        ExchangeRate(currency: "GGP", rate: 0.7491, fluctuation: .decrease),
        ExchangeRate(currency: "GHS", rate: 15.4982, fluctuation: .increase),
        ExchangeRate(currency: "GIP", rate: 0.7594, fluctuation: .increase),
        ExchangeRate(currency: "GMD", rate: 72.7721, fluctuation: .increase),
        ExchangeRate(currency: "GNF", rate: 8739.1246, fluctuation: .decrease),
        ExchangeRate(currency: "GTQ", rate: 7.7068, fluctuation: .decrease),
        ExchangeRate(currency: "GYD", rate: 209.9092, fluctuation: .increase),
        ExchangeRate(currency: "HKD", rate: 7.7712, fluctuation: .increase),
        ExchangeRate(currency: "HNL", rate: 25.8921, fluctuation: .decrease),
        ExchangeRate(currency: "HRK", rate: 6.6021, fluctuation: .increase),
        ExchangeRate(currency: "HTG", rate: 130.8245, fluctuation: .increase),
        ExchangeRate(currency: "HUF", rate: 357.0912, fluctuation: .decrease),
        ExchangeRate(currency: "IDR", rate: 16856.5721, fluctuation: .increase),
        ExchangeRate(currency: "ILS", rate: 3.6737, fluctuation: .decrease),
        ExchangeRate(currency: "IMP", rate: 0.7498, fluctuation: .decrease),
        ExchangeRate(currency: "INR", rate: 85.6081, fluctuation: .increase),
        ExchangeRate(currency: "IQD", rate: 1310.2945, fluctuation: .decrease),
        ExchangeRate(currency: "IRR", rate: 42011.4912, fluctuation: .decrease),
        ExchangeRate(currency: "ISK", rate: 127.7216, fluctuation: .increase),
        ExchangeRate(currency: "JEP", rate: 0.7492, fluctuation: .decrease),
        ExchangeRate(currency: "JMD", rate: 157.8921, fluctuation: .decrease),
        ExchangeRate(currency: "JOD", rate: 0.7179, fluctuation: .increase),
        ExchangeRate(currency: "JPY", rate: 141.8243, fluctuation: .increase),
        ExchangeRate(currency: "KES", rate: 129.7212, fluctuation: .increase),
        ExchangeRate(currency: "KGS", rate: 87.2152, fluctuation: .decrease),
        ExchangeRate(currency: "KHR", rate: 3983.9271, fluctuation: .increase),
        ExchangeRate(currency: "KID", rate: 1.5731, fluctuation: .increase),
        ExchangeRate(currency: "KMF", rate: 430.5921, fluctuation: .decrease),
        ExchangeRate(currency: "KRW", rate: 1422.1742, fluctuation: .increase),
        ExchangeRate(currency: "KWD", rate: 0.3102, fluctuation: .increase),
        ExchangeRate(currency: "KYD", rate: 0.8392, fluctuation: .increase),
        ExchangeRate(currency: "KZT", rate: 522.6721, fluctuation: .increase),
        ExchangeRate(currency: "LAK", rate: 21758.3921, fluctuation: .decrease),
        ExchangeRate(currency: "LBP", rate: 89499.7831, fluctuation: .decrease),
        ExchangeRate(currency: "LKR", rate: 298.5723, fluctuation: .decrease),
        ExchangeRate(currency: "LRD", rate: 200.0782, fluctuation: .increase),
        ExchangeRate(currency: "LSL", rate: 18.7982, fluctuation: .decrease),
        ExchangeRate(currency: "LYD", rate: 5.4832, fluctuation: .increase),
        ExchangeRate(currency: "MAD", rate: 9.2751, fluctuation: .decrease),
        ExchangeRate(currency: "MDL", rate: 17.2912, fluctuation: .decrease),
        ExchangeRate(currency: "MGA", rate: 4573.4721, fluctuation: .decrease),
        ExchangeRate(currency: "MKD", rate: 54.1892, fluctuation: .increase),
        ExchangeRate(currency: "MMK", rate: 2099.9214, fluctuation: .increase),
        ExchangeRate(currency: "MNT", rate: 3560.7213, fluctuation: .increase),
        ExchangeRate(currency: "MOP", rate: 7.9982, fluctuation: .increase),
        ExchangeRate(currency: "MRU", rate: 39.6982, fluctuation: .increase),
        ExchangeRate(currency: "MUR", rate: 45.0823, fluctuation: .increase),
        ExchangeRate(currency: "MVR", rate: 15.4682, fluctuation: .increase),
        ExchangeRate(currency: "MWK", rate: 1735.1245, fluctuation: .increase),
        ExchangeRate(currency: "MXN", rate: 19.7921, fluctuation: .increase),
        ExchangeRate(currency: "MYR", rate: 4.4237, fluctuation: .increase),
        ExchangeRate(currency: "MZN", rate: 63.7245, fluctuation: .increase),
        ExchangeRate(currency: "NAD", rate: 18.8912, fluctuation: .increase),
        ExchangeRate(currency: "NGN", rate: 1604.7215, fluctuation: .increase),
        ExchangeRate(currency: "NIO", rate: 36.8245, fluctuation: .increase),
        ExchangeRate(currency: "NOK", rate: 10.4672, fluctuation: .increase),
        ExchangeRate(currency: "NPR", rate: 136.7924, fluctuation: .decrease),
        ExchangeRate(currency: "NZD", rate: 1.6921, fluctuation: .increase),
        ExchangeRate(currency: "OMR", rate: 0.3892, fluctuation: .increase),
        ExchangeRate(currency: "PAB", rate: 1.0214, fluctuation: .increase),
        ExchangeRate(currency: "PEN", rate: 3.7521, fluctuation: .increase),
        ExchangeRate(currency: "PGK", rate: 4.1421, fluctuation: .increase),
        ExchangeRate(currency: "PHP", rate: 56.7852, fluctuation: .increase),
        ExchangeRate(currency: "PKR", rate: 280.2981, fluctuation: .decrease),
        ExchangeRate(currency: "PLN", rate: 3.7592, fluctuation: .increase),
        ExchangeRate(currency: "PYG", rate: 8032.1783, fluctuation: .decrease),
        ExchangeRate(currency: "QAR", rate: 3.6492, fluctuation: .increase),
        ExchangeRate(currency: "RON", rate: 4.3872, fluctuation: .increase),
        ExchangeRate(currency: "RSD", rate: 103.0982, fluctuation: .decrease),
        ExchangeRate(currency: "RUB", rate: 82.0673, fluctuation: .increase),
        ExchangeRate(currency: "RWF", rate: 1448.0782, fluctuation: .decrease),
        ExchangeRate(currency: "SAR", rate: 3.7621, fluctuation: .increase),
        ExchangeRate(currency: "SBD", rate: 8.5482, fluctuation: .decrease),
        ExchangeRate(currency: "SCR", rate: 14.2982, fluctuation: .increase),
        ExchangeRate(currency: "SDG", rate: 458.6721, fluctuation: .increase),
        ExchangeRate(currency: "SEK", rate: 9.5983, fluctuation: .increase),
        ExchangeRate(currency: "SGD", rate: 1.3121, fluctuation: .increase),
        ExchangeRate(currency: "SHP", rate: 0.7583, fluctuation: .increase),
        ExchangeRate(currency: "SLE", rate: 22.7921, fluctuation: .increase),
        ExchangeRate(currency: "SLL", rate: 22781.9273, fluctuation: .increase),
        ExchangeRate(currency: "SOS", rate: 572.0872, fluctuation: .increase),
        ExchangeRate(currency: "SRD", rate: 36.8983, fluctuation: .increase),
        ExchangeRate(currency: "SSP", rate: 4528.3921, fluctuation: .increase),
        ExchangeRate(currency: "STN", rate: 21.4572, fluctuation: .increase),
        ExchangeRate(currency: "SYP", rate: 12887.9153, fluctuation: .increase),
        ExchangeRate(currency: "SZL", rate: 18.8392, fluctuation: .increase),
        ExchangeRate(currency: "THB", rate: 33.3721, fluctuation: .increase),
        ExchangeRate(currency: "TJS", rate: 10.8752, fluctuation: .increase),
        ExchangeRate(currency: "TMT", rate: 3.5092, fluctuation: .increase),
        ExchangeRate(currency: "TND", rate: 2.9921, fluctuation: .increase),
        ExchangeRate(currency: "TOP", rate: 2.3921, fluctuation: .increase),
        ExchangeRate(currency: "TRY", rate: 38.1891, fluctuation: .increase),
        ExchangeRate(currency: "TTD", rate: 6.7921, fluctuation: .increase),
        ExchangeRate(currency: "TVD", rate: 1.5721, fluctuation: .increase),
        ExchangeRate(currency: "TWD", rate: 32.5092, fluctuation: .increase),
        ExchangeRate(currency: "TZS", rate: 2689.0721, fluctuation: .increase),
        ExchangeRate(currency: "UAH", rate: 41.4125, fluctuation: .increase),
        ExchangeRate(currency: "UGX", rate: 3653.6217, fluctuation: .increase),
        ExchangeRate(currency: "UYU", rate: 42.2819, fluctuation: .increase),
        ExchangeRate(currency: "UZS", rate: 12975.0253, fluctuation: .increase),
        ExchangeRate(currency: "VES", rate: 81.0217, fluctuation: .increase),
        ExchangeRate(currency: "VND", rate: 25935.6735, fluctuation: .increase),
        ExchangeRate(currency: "VUV", rate: 120.3952, fluctuation: .increase),
        ExchangeRate(currency: "WST", rate: 2.7821, fluctuation: .increase),
        ExchangeRate(currency: "XAF", rate: 574.2871, fluctuation: .increase),
        ExchangeRate(currency: "XCD", rate: 2.7082, fluctuation: .increase),
        ExchangeRate(currency: "XCG", rate: 1.7982, fluctuation: .increase),
        ExchangeRate(currency: "XDR", rate: 0.7421, fluctuation: .increase),
        ExchangeRate(currency: "XOF", rate: 574.2531, fluctuation: .increase),
        ExchangeRate(currency: "XPF", rate: 104.5217, fluctuation: .increase),
        ExchangeRate(currency: "YER", rate: 245.2437, fluctuation: .increase),
        ExchangeRate(currency: "ZAR", rate: 18.8273, fluctuation: .increase),
        ExchangeRate(currency: "ZMW", rate: 28.6125, fluctuation: .increase),
        ExchangeRate(currency: "ZWL", rate: 26.8235, fluctuation: .increase)
    ]
}
